### ISSUE TITLE
Analysis view: Not representing multiple platforms in group:

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#1316]
### Description

Running a workflow where multiple tasks are assigned platforms within a group the analysis view shows all jobs as being run by the first platform in the group to run a task:

In my example jobs have run (I checked with the job activity log - it's not super obvious after the fact in the GUI) on platforms "aleph" and "bet". `onPbs_n2` and `onPbs_n4` both ran on `aleph`, but are shown as having run on `bet`. Aleph is not available from the filter drop down.

![analbug](https://github.com/cylc/cylc-ui/assets/26465611/3341d0bc-55c1-4973-822a-494cdb0d95a8)

### Reproducible Example

```ini
# global.cylc
[platforms]
    [[aleph]]
        install target = aleph1
        hosts = aleph1, aleph2
        job runner = pbs

    [[bet]]
        install target = bet1
        hosts = bet1, bet2
        job runner = pbs

[platform groups]
    [[mygroup]]
        platforms = aleph, bet
```

```ini
# flow.cylc
[task parameters]
    # enough tasks that both platforms very likely (98% per cycle) to be used.
    n = 1..6   

[scheduler]
    allow implicit tasks = True

[scheduling]
    initial cycle point = 1610
    final cycle point = 1612
    [[graph]]
        P1Y = onPbs<n>
```

**Comment by oliver-sanders** [comment]
The analysis view runs off of task defs not task proxies because its purpose is to provide statistical analysis.

This means that a task that is run on multiple platforms will still be represented by a single row in the DB which is pretty much unavoidable. Things which could cause a task to submit to multiple platforms over a workflow run:
* Reloads.
* Broadcasts.
* Platform groups.
* Platform selection commands.

Ways of handing this:

1. Do nothing.
2. Split the task into multiple rows representing each platform.
3. Show all platforms a task has submitted to in the platform field (adding an extra option to the platform selection dropdown).

TBH, I think (1) is fairly reasonable. Differences in platform performance can be picked up with a run-time/cycle-time graph (planned).
