### ISSUE TITLE
Graph view: place arrowheads in middle of graph edge?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1424]
### Problem

In the graph view the arrowheads can overlap or point at a slightly odd angle at the end. 

![image](https://github.com/cylc/cylc-ui/assets/61982285/48d633ab-9014-4069-9260-24f1024f861e)

### Proposed Solution

Place the arrowheads in the middle of the line, if that's possible.

**Comment by oliver-sanders** [comment]
I did have a crack at this when implementing the graph view, note those lines and arrow positions come from Graphviz.

What we could do, is to draw the arrow where we want it, and bodge the line Graphviz gives us to route it into the arrow head. This saves on multiple arrow heads, but it leaves us with lines coming in at strange angles to the same arrow head which is really confusing. E.G. in the example above the lines arriving at "failed" come in at 90 degrees to each other.

To get the lines coming in at the right angle we would need to add a control point, but because these are quadratic curves, doing this could potentially result in strange artefacts so would need to be done very carefully.

IMO the status quo is plenty good enough.

**Comment by hjoliver** [comment]
It sounds as if this would be more work than it's worth (and it has the potential for reducing performance?). Close as won't fix?

**Comment by oliver-sanders** [comment]
That's my feeling, the priority of this work is too far down the ladder to warrant keeping a ticket for it.
