### ISSUE TITLE
Remove files that require Internet connection

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#386]
**Describe the bug**

Off the top of my head, we have FontAwesome being removed in #383 , but also the Roboto webfont.

These files will result in a 404 in environments such as HPC with restrictions to access external resources.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Access the UI and check the resources downloaded.

**Expected behavior**

Everything being served from wherever Cylc UI was installed only.

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Regarding the webfont, we might be able to choose a good font that works on mac/win/linux (e.g. this [article](https://websitesetup.org/web-safe-fonts-html-css/) on web safe fonts)

**Comment by hjoliver** [comment]
Is that article suggesting (it wasn't entirely clear to me) falling back to a locally-installed font, or not using web fonts at all?

I'd be reluctant to use some ugly lowest-common-denominator font just because everyone has it installed on their systems.  Instead, can we either:
- use a webfont but fall back to a local font if we don't have internet access
- or download the webfont and bundle it with our UI?

**Comment by kinow** [comment]
>or download the webfont and bundle it with our UI?

Oh, didn't think about that. Good idea! https://github.com/cylc/cylc-ui/pull/406
