### ISSUE TITLE
Tree: don't split between task icon and name

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#394]
Minor issue; affects long task names and/or narrow tab widths:

![shot](https://user-images.githubusercontent.com/2362137/73497237-327dc680-441f-11ea-8bb6-36d6e7eb94fb.png)

**Comment by kinow** [comment]
Probably fixed by #396 @hjoliver 

Quickly altered an HTML element to have a long name, and then switched to that branch, and it seems to have fixed this issue too.

![image](https://user-images.githubusercontent.com/304786/73518468-477c4900-4463-11ea-9547-f0da04b1bb5a.png)

![image](https://user-images.githubusercontent.com/304786/73518484-55ca6500-4463-11ea-8929-eebd96661205.png)

**Comment by kinow** [comment]
(I've added the "close #blablabla" to that issue already :sweat_smile: )

**Comment by hjoliver** [comment]
Great, thanks @kinow :+1:
