### ISSUE TITLE
cylc graph, cylc gui graph view: nice way to specify node images 

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc-ui#55]
We can use the `image` node attribute to draw images within nodes in
`cylc graph` and the `cylc gui` graph view. In fact, you can already embed
an image within nodes for `cylc graph` in the visualization section (add:
`image="/some/path/to/image.png", imagescale="both"` to a task in `[[node attributes]]`.

It would be best if we could get the image to avoid the text in the node (top right?).

**Comment by kinow** [comment]
Note after migration to cylc-web discussion:

>   * (Hilary) Agreed. Maybe. But very low priority.

**Comment by oliver-sanders** [comment]
Do we still want to consider this?

**Comment by sadielbartholomew** [comment]
> Do we still want to consider this?

I vote no; I anticipate some users may benefit from a non-textual indicator along with, or to replace, task names in a node, but I cannot see any pressing use case for embedding any arbitrary image. In light of that, could we support, along with text as standard, just **a set of icons instead** (via a direct means i.e. ``icon=atlas`` which applies ``fa-atlas``)? Perhaps anything from a common set such as the free sub-set of Font Awesome (as per the previous example)?

Benefits to the above:

* it allows for *some* customisation, but not *too much* (as I believe is the aim from UI/UX theory);
* we can (in establishing support for this) control the dimensions & positioning easily, given the standardised (& near-square) size of the icons;
* we can support suite.rc ``[visualization]`` configuration of the styling without difficulty, since colour & opacity are easy to set via CSS for the icons so we just need to link up to that;
* scaling & customisation are provided out-of-the-box.

**Comment by hjoliver** [comment]
I can't see people being bothered to use images for all task nodes; it would look messy anyway; and text task-name would be pretty much required as well unless every image was different (which ain't gonna happen).  Further, this would break this our planned nice uniformity of task and job status icons in all views, for the new UI.

So I vote close this.

**Comment by oliver-sanders** [comment]
> So I vote close this.

+1

> it would look messy anyway

Definitely

> I can't see people being bothered to use images for all task nodes

We support widget images in Rose Config, I think only two projects have actually used this feature.
