### ISSUE TITLE
Dashboard skeleton loader: page jump

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#660]
A minor but annoying design problem:

I often go to the Dashboard page with the sole intention of clicking on one of the static links (e.g. preferences or hub), then accidentally hit the wrong link when the real Workflows data suddenly replaces the skeleton, which moves the static links downward.

![shot](https://user-images.githubusercontent.com/2362137/116831880-28400e80-ac06-11eb-8e26-ba1e4ca4fb47.png)

I wonder if we should:
1. make the loader the exact same height as the data table
   -  (but this might not work depending on what gets displayed under Events at the top right side)
1. or put the static links at the top of the page

Thoughts anyone?

**Comment by kinow** [comment]
Oh, that's indeed very bad, it's called Content Shifting or Content Jumping, and I also hate it (Twitter has this problem in the UI). Defining the future height of the component can work, though it could still change slightly depending on how we implement and maybe on the browser too.

Moving the static content to the top would definitely fix it, but I think most times users will want to see those numbers, instead of clicking on the links.

We can try the first option of setting the height and see how that works IMO. Will wait to see what @oliver-sanders and others think.

**Comment by oliver-sanders** [comment]
Long term we can probably turn these different sections into Lumino widgets (and chuck in a GraphiQL widget, etc) and let users arrange them however they wish.
