### ISSUE TITLE
gscan: installed workflows

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#688]
GScan no longer displays all "stopped" workflows because some workflows that are stopped have the status "INSTALLED".

We could fix this by adding "INSTALLED" to the list of the filtered states in GScan, however, I wonder if we can handle this differently...

The distinction between "INSTALLED" and "STOPPED" is quite subtle:

* **INSTALLED** Not currently running *and* hasn't run before.
* **STOPPED** Not currently running *but* has run before.

I can't remember why we [introduced the distinction](https://github.com/cylc/cylc-flow/pull/4206/files#diff-03bc1d330de598ad6b24fde7fdf98f2ad79f2f36b5fbaf8748bfb2b862cea0a8R43-R44). I think it will be confusing to users when they are filtering workflows by state. Cylc doesn't make this distinction anywhere else, for example `cylc scan` shows these "INSTALLED" flows as "STOPPED". If we need to preserve the information that the workflow has/hasn't run before we could consider adding a dedicated "(re)start number" field (like the one we log this number on workflow start).

Ideas?

**Comment by kinow** [comment]
The GScan Deltas branch should be displaying the installed workflows now (ready for final review in a few more days, just fixing tests, and doing some more manual testing). Can't comment much more whether it makes sense to have the two states or not though.

**Comment by oliver-sanders** [comment]
Just realised this is fixed by the GScan branch 🤦.

Workaround / fix on #543

**Comment by hjoliver** [comment]
I can't remember the original discussion either.  

I think the problem is these "workflow states" are really overlapping categories, not mutually exclusive.

Filtering for "installed" should show all workflows in the `cylc-run` directory regardless of state (but no source workflows in `cylc-src` dir etc.)

I guess we could decide to interpret "stopped" as simply "not running" but that is potentially confusing. Is a recorded song (say) "stopped" if it's never been played yet? :thinking: 

It might be more sensible to have overlapping filter categories:
- installed (all installed workflows)
- stopped (all workflows that ran before but are currently stopped)
- not-running (all workflows that are not running)
- (plus the more obvious ones: source, running, paused)

**Comment by oliver-sanders** [comment]
This is getting complicated. I don't think we actually need to differentiate between "installed" and "stopped".

> I guess we could decide to interpret "stopped" as simply "not running" but that is potentially confusing

I think it's less confusing than having an overlapping states and exposing that in the relevant filter interfaces.

In the tape-deck model "stopped" makes sense, tapes are loaded as workflows are installed, in the "stopped" state:

* !Running => Stopped
* Running & !Active => Paused
* Running & Active => Running

**Comment by hjoliver** [comment]
IMO It would sometimes be mildly useful to distinguish between stopped and never-ran.

Actually gscan state summaries (once implemented for stopped workflows) will help with that though.

But my main beef was that“installed” as it is now is definitely wrong. Installed must mean any installed workflow, not jsu installed ones that have not been run yet.

**Comment by oliver-sanders** [comment]
> IMO It would sometimes be mildly useful to distinguish between stopped and never-ran.

True, I think a "re(start) number" field (like the one in the log) might be a good way to go about this.

**Comment by hjoliver** [comment]
OK, I reckon the following categories cover everything that users might want to know:
- **source** - all workflows in configured source dirs (`cylc-src` etc.)
- **installed** - all workflows in `cylc-run`
- **running** - (what it says)
- **paused** - (what it says)
- **never-ran** - (what it says) 
- **completed** - ran to completion (and so can't be restarted)
- **killed** (or **died?**) - ran but did not shut down cleanly (external kill or internal bug)
- **shut-down** - ran but shut down cleanly (completed, or told to stop) 
- **not-running** - (what it says)

There is some overlap in these categories, and there's quite a few of them, but it seems to me they're all potentially useful information that users could benefit from.

We could choose to combine some of these for simplicity, but at the cost of losing some information and possibly introducing some ambiguity (which could be mitigated with good naming and good documentation, of course).

I guess we hadn't really thought this through properly before.

**Comment by hjoliver** [comment]
We might need to agree on something more minimal for 8.0 however!  To be enhanced later.

**Comment by hjoliver** [comment]
Minimal but self-consistent:
- **running** and **paused**
- **not-running** 
- **source** ("installed" is not-**source**)

"not-running" is unambiguous, unlike "stopped" (although, do we consider paused to be not-running?  Probably yes, because users don't need to care if there's a running scheduler or not)

installed-but-never-ran is another possibility already, as that's what we have now as "installed".

**Comment by oliver-sanders** [comment]
Potential to rethink after 8.0.0 if there are pressing reasons to change.

> Sorry to make this more complicated!

Yikes!

I think we should keep the number of states small and the model simple. Surplus information (such how many times the workflow has started up, whether it was installed [by cylc], etc) can be provided in other ways (e.g. tooltips or the workflow status line). No need to make the status field convey everything, that could get confusing (e.g. installed/not-installed and running/stopped are orthogonal states).

"not-running" is ok, though it does overlap with paused as you mentioned.

I get the temptation to rename things, however, I think renaming the "stopped" state because it's slightly grammatically clumsy is perhaps being overly technically correct (he says using notably clumsy grammar). Users are probably going to better understand the states they are already working with (workflows being installed into the "stopped" state with `rose suite-run`).

I would want to keep the current model of running,paused,stopping,stopped but add an uninstalled state in later for source workflow detection.

**Comment by hjoliver** [comment]
Maybe I wasn't very clear above.  

> OK, I reckon the following categories cover everything that users might want to know:

I wasn't actually suggesting everything in that list needs to be a "state" with a corresponding icon in gscan, but that it's all information that users with lots of workflows might want to be able to get at via gscan.

We could have a tooltip over a stopped workflow that shows number of (re)starts (as you noted) but also whether it ran to completion (i.e. shut down with nothing else to do) or was stopped prematurely, or was killed.  And, that information could be used in filtering too.  

If we settle on the minimal set of actual states, it would be easy to extend tool tips and filtering later.

**Comment by hjoliver** [comment]
So with orthogonals/opposites removed, I think it boils down to this, with **state** in bold, and sub-states(?) for *tooltips* and possibly *filtering*: 

- **running**
  - stopping
- **paused**
  - stopping
- **stopped** 
  - number of (re)starts
  - completed
  - killed or crashed
- **source**
 
Note:
- **paused** is arguably a sub-state of **running**
   - but I guess in the tape-deck model it makes more sense as a full-blown state?
- "installed" is *not*-**source**
- "never ran" is **stopped** with *zero starts*

So that's actually quite un-complicated! 
 
I think all we need to do is:
- change the current incorrect "installed" state to "stopped"
- enhance the gscan UI with metadata-based tooltips and filtering later
 
(I'm happy with **stopped** meaning "not-running", in the tape-deck model, so long as we document that it includes never-ran).

**Comment by kinow** [comment]
Waiting for GH Actions e2e tests to finish, so catching up with this issue :) Looks good to me, the proposal above.

@hjoliver , If a workflow is stalled in Cylc Flow, then in the UI it will be running?

And if a workflow failed in Cylc Flow, then in the UI it will be stopped + crashed?
