### ISSUE TITLE
Received a delta before the workflow initial data burst

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#689]
**Describe the bug**

Error message in the console and displayed using the error banner:

> Received a delta before the workflow initial data burst. Please reload your browser tab to retrieve the full flow state

**Steps to reproduce the bug**

1. Open the tree view at a running workflow
2. Stop the workflow (wait for UI to update)
3. Play the workfow.

**Additional context**

This diff shows that the error is caused by an empty delta:

```diff
diff --git a/src/components/cylc/tree/deltas.js b/src/components/cylc/tree/deltas.js
index b953f9ce..a14a16a8 100644
--- a/src/components/cylc/tree/deltas.js
+++ b/src/components/cylc/tree/deltas.js
@@ -220,6 +220,7 @@ export function applyDeltas (deltas, tree) {
       // page. So we fail silently and wait for a request with the initial data.
       if (!deltas.added || !deltas.added.workflow) {
         // eslint-disable-next-line no-console
+        console.error(deltas)
         console.error('Received a delta before the workflow initial data burst')
         store.dispatch('setAlert', new AlertModel('Received a delta before the workflow initial data burst. Please reload your browser tab to retrieve the full flow state', null, 'error'))
         return
```

```
{"id": "2", "type": "data", "payload": {"data": {"deltas": {"id": "oliver|one", "shutdown": true, "added": {"__typename": "Added"}, "updated": {"__typename": "Updated"}, "pruned": {"__typename": "Pruned"}, "__typename": "Deltas"}}}}	1624270854.4726202
```

I can't tell if the delta being sent relates to the previous run or the new one so the error might be legitimate.

As the subscription uses `stripNull=true` I think this becomes a UIS issue?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Ah, I'll update the GScan branch to use `console.log('Error message the same followed by...', deltas)

So that the deltas Object structure & data are printed with the error, to make reporting errors a bit easier. Thanks for creating this issue!

**Comment by dwsutherland** [comment]
Has the gscan deltas gone in yet, this delta pertains to this:
https://github.com/cylc/cylc-uiserver/blob/a6c5aad2dd9df7533efc2b95a52ae737dbfdff2f/cylc/uiserver/data_store_mgr.py#L226-L229

So, it sends a shutdown delta.. I don't see anything too wrong with this (remember pruned is different than shutdown).
Has the UI workflow pruning gone in yet?

So the UI will need read the `deltas.shutdown` flag. there might (?) be a change in status `running => stopped`.. So if we want to not use this flag, we can remove that block (and the UIS subscribed topic)

@kinow - Thoughts?

**Comment by kinow** [comment]
@dwsutherland I am finishing to fix e2e tests, then will start adding tests for the gscan deltas. Finally getting close to the final version.

Once I've got everything working and tested, I will check on that branch whether I'm getting an extra delta or not. Note that in that branch, I'm replacing the tree deltas query subscription that used `workflow { taskProxies { jobs } }` by a flat query with `{ workflow {} taskProxies {} jobs {} }`.

I think we had suspected that that deep structure could be related to the extra delta.

**Comment by dwsutherland** [comment]
The delta that @oliver-sanders  specified is the shutdown delta (as I described)... nothing mysterious about it.. It's actually received after shutdown (or should be), but interpreted by the front end as an empty initial/pre-initial burst delta.

**Comment by kinow** [comment]
> The delta that @oliver-sanders specified is the shutdown delta (as I described)... nothing mysterious about it.. It's actually received after shutdown (or should be), but interpreted by the front end as an empty initial/pre-initial burst delta.

Aaahhh! Now I see!

>"shutdown": true

Sorry @dwsutherland , thought we were discussing something else. Let me hide my off-topic comments here :grimacing:

**Comment by kinow** [comment]
Let me test that in the GScan deltas branch to see how it behaves.

**Comment by kinow** [comment]
@dwsutherland the UI complains because after the delta with `shutdown: true`, there is one more delta (using master on Cylc Flow & UIServer).

![image](https://user-images.githubusercontent.com/304786/123191436-5a2e6c80-d4f5-11eb-89e6-3279937c2684.png)

Would it be possible to filter these empty deltas in the server, just before sending it to the subscriber? That would solve this issue I think. WDYT?

**Comment by dwsutherland** [comment]
We need to look at exactly where they are produced and why.. Then we will be able to say whether or not they should be sent, and how the UI should handle them if it needs to.

**Comment by dwsutherland** [comment]
So, there are two shutdown/stopped messages:
- One from the Scheduler `deltas.shutdown` (value `true`), which is published during the shutdown procedure as the scheduler's last dying breath.
- Another from the UIS `deltas.updated.workflow.status`, which is generated after the scan discovers the workflow is no longer running and purges it.

At the moment, gscan deltas are looking for `deltas.shutdown` which arrives first then gets the `deltas.updated.workflow.status` delta afterwards and mistakes it for an initial burst.

We should use `deltas.updated.workflow.status`, and just ignore the first one... This will be the safer option too, because sometimes the Scheduler doesn't get the chance to publish on it's death bed.. Sometimes the Scheduler process will just get killed.

As for the publishing empties; stripping is not natural for GraphQL (it's something we invented), and unless we meddle with more of the underlying libraries, I think post async gen yield the code will always send something to push (even if it's `None`).

**Comment by kinow** [comment]
Will try the approach described by @dwsutherland after the GScan PR is reviewed/merged. Shouldn't be too hard to implement it :crossed_fingers: and thanks @dwsutherland again for helping with this.

**Comment by kinow** [comment]
Will work on this one before finishing the Table view (pending #699 ).

**Comment by kinow** [comment]
@dwsutherland I think relying on the workflow state worked! At least manual tests all passed (stopped running workflow, cold-started it; paused workflow, started again). Will need to update tests, maybe write new ones. But will spend some time thinking about possible scenarios for this change to confirm I'm not missing anything.

Thanks!
