### ISSUE TITLE
slow to load with large numbers of workflows

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#866]
When you start the GUI the number of workflows displayed on the dashboard, starting at 0 and incrementing one by one.

It's a fairly fast process, however, if you have > ~30 workflows it takes a little while. The GUI is somewhat unresponsive during this period.

We should do something to improve this load time.

I think the cause is probably the delta processing time.

A possible solution would be to batch up the workflow-added deltas at the UIS so that all workflows arrive together at startup. This might cut out render stage from the workflow-added loop?

**Pull requests welcome!**

**Comment by kinow** [comment]
>A possible solution would be to batch up the workflow-added deltas at the UIS so that all workflows arrive together at startup. This might cut out render stage from the workflow-added loop?

I think this would be a good fix. Maybe in the future, if needed, the updated/pruned deltas could be batched and the throughput controlled in the UIS too (i.e. accumulate these deltas types and send to the UI every 300ms or some other configured interval, instead of sending everything whenever it's available).

That could reduce the number of times the UI needs to process messages from the UIS, update internal data, and tell Vue to update the VDOM and DOM too.

**Comment by oliver-sanders** [comment]
Closing this in favour of the more detailed #947
